language: objective-c

rvm:
  - 2.2.1

cache:
  - bundler

before_install:
  - gem install bundler
  - brew install coreutils
  - npm install -g coffee-script
  - mkdir dist

install:
  - bundle install

script:
  - rake test:cli
  - rake test:web:ci

notifications:
  recipients:
    - yeannylam@gmail.com